name: continuous integration
on: [push, pull_request]
# These keys should match the keys in .env.template
env:
  AFFILS_DB_ENGINE: "postgresql"
  AFFILS_DB_NAME: "postgres"
  AFFILS_DB_USER: "postgres"
  AFFILS_DB_PASSWORD: "postgres"
  AFFILS_DB_HOST: "127.0.0.1"
  AFFILS_DB_PORT: "5432"
  AFFILS_WORKING_DIR: ${{ github.workspace }}
  AFFILS_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AFFILS_AWS_REGION: ${{ secrets.AWS_REGION }}
  AFFILS_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install Pipenv
        run: pip install pipenv --user
      - name: install dependencies
        run: pipenv sync --dev # Installs all deps, including dev deps, from Pipfile.lock.
      - name: format
        run: pipenv run invoke fmtcheck
      - name: lint
        run: pipenv run invoke lint
      - name: check types
        run: pipenv run invoke types
      - name: run tests
        run: pipenv run invoke test
